### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by Qi-Zhangyang** [ZiyuGuo99/Point-Bind_Point-LLM#2]
There is no requirements.txt in the repo.

**Comment by ZiyuGuo99** [comment]
@Qi-Zhangyang Apologies for the delay. Thanks for your interest and reminder! : )
We have added the [requirements.txt](https://github.com/ZiyuGuo99/Point-Bind_Point-LLM/blob/main/requirements.txt) file.
