### ISSUE TITLE
pretrained weights of point-bind

### ISSUE THREAD

**Issue by auniquesun** [ZiyuGuo99/Point-Bind_Point-LLM#4]
Thanks for sharing the great project! This project associates 3d with more modalities than before thus gains more benefits.

I wonder could you also share the pretrained weights of point-bind? E.g., i2p-mae.pt and pointbert.pt

Thanks.

**Comment by ZiyuGuo99** [comment]
@auniquesun Sorry for the late reply, and thanks for your interest. : )
Please kindly refer to [Install.md](https://github.com/ZiyuGuo99/Point-Bind_Point-LLM/blob/main/Install.md) for the download links of the pre-trained weights, i.e., pointbind_i2pmae.pt and pointbind_pointbert.pt.

**Comment by auniquesun** [comment]
Thanks. This is a great work, I will try it.
