### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by joseigbintuitivo** [ZiyuGuo99/Point-Bind_Point-LLM#5]
Hello, first of all thank you for sharing your amazing work

I'm trying to upload a pointcloud to the demo web, but it gets stuck uploading and never finishes. I tried with multiple pointcloud, .ply format.

**Comment by ZiyuGuo99** [comment]
@joseigbintuitivo Thanks for your interest.
The issue may be due to the size of the uploaded point cloud. For smoother processing, we recommend keeping your point cloud data under 1MB.
