### ISSUE TITLE
The points' format

### ISSUE THREAD

**Issue by Marmiya** [ZiyuGuo99/Point-Bind_Point-LLM#7]
There are airplane.pt, examples/car.pt, and examples/toilet.pt in the example.
But I have never seen this format of point cloud.
How can I test my own point clouds?

**Comment by ZiyuGuo99** [comment]
@Marmiya Thanks for your interest in our work. 
You can indeed evaluate your own point clouds by utilizing the data loading code specific to your data format. For reference, you can check line 165 in [this file](https://github.com/OpenGVLab/LLaMA-Adapter/blob/main/imagebind_LLM/ImageBind/data.py) of Point-LLM.

**Comment by Marmiya** [comment]
Thanks for your reply.
Good work :D
